cmake_minimum_required(VERSION 4.0)
project(PC3)

set(CMAKE_CXX_STANDARD 20)

add_executable(main main.cpp)
add_executable(struct1.0 struct1.0.cpp)

add_executable(cajita1.0 cajitas/cajita1.0.cpp)
add_executable(cajita1.1 cajitas/cajita1.1.cpp)
add_executable(cajita1.2 cajitas/cajita1.2.cpp)
add_executable(cajita1.3 cajitas/cajita1.3.cpp)
add_executable(cajita1.4 cajitas/cajita1.4.cpp)
add_executable(cajita2.0 cajitas/cajita2.0.cpp)


add_executable(2024.2.P1 2024.2.P1.cpp)
add_executable(2024.2.P2 2024.2.P2.cpp)
add_executable(2024.2.P3 2024.2.P3.cpp)

add_executable(2025.1.P1 2025.1.P1.cpp)
add_executable(2025.1.P2 2025.1.P2.cpp)
add_executable(2025.1.P3 2025.1.P3.cpp)

add_executable(p1 sebastian.mogollon.p1.cpp)
add_executable(p1.1 sebastian.mogollon.f.p1.cpp)

add_executable(p2 sebastian.mogollon.p2.cpp)
add_executable(p3 sebastian.mogollon.p3.cpp)
