cmake_minimum_required(VERSION 4.0)
project(PARCIAL)

set(CMAKE_CXX_STANDARD 20)

add_executable(2024_II_PARCIAL_P1 2024_II_PARCIAL_P1.cpp)
add_executable(2024_II_PARCIAL_P2 2024_II_PARCIAL_P2.cpp)
add_executable(2024_II_PARCIAL_P3 2024_II_PARCIAL_P3.cpp)

add_executable(2025_I_PARCIAL_P1 2025_I_PARCIAL_P1.cpp)
add_executable(2025_I_PARCIAL_P2 2025_I_PARCIAL_P2.cpp)
add_executable(2025_I_PARCIAL_P3 2025_I_PARCIAL_P3.cpp)

add_executable(sparring1 sparring1.cpp)
add_executable(sparring2 sparring2.cpp)
add_executable(sparring3 sparring3.cpp)
add_executable(sparring4 sparring4.cpp)
add_executable(sparring5 sparring5.cpp)
add_executable(sparring6 sparring6.cpp)
add_executable(sparring7 sparring7.cpp)
add_executable(sparring8 sparring8.cpp)

add_executable(p1 mogollon-sebastian-ep-p1.cpp)
add_executable(p2 mogollon-sebastian-ep-p2.cpp)
add_executable(p3 mogollon-sebastian-ep-p3.cpp)


